# Generated by Django 4.2.27 on 2026-01-26 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUbsMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubs_memberships', to='auth.group')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.ubs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubs_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ubs_memberships',
                'indexes': [models.Index(fields=['user', 'active'], name='user_ubs_me_user_id_05ce9e_idx'), models.Index(fields=['ubs', 'active'], name='user_ubs_me_ubs_id_c3aa7c_idx'), models.Index(fields=['group'], name='user_ubs_me_group_i_a547e4_idx')],
                'unique_together': {('user', 'ubs', 'group')},
            },
        ),
    ]
