# Generated by Django 4.2.27 on 2026-01-26 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_locations', to='core.ubs')),
            ],
            options={
                'db_table': 'stock_locations',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entry'), ('OUT', 'Out'), ('TRANSFER', 'Transfer'), ('ADJUST', 'Adjust'), ('REVERSAL', 'Reversal')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=16)),
                ('reference_type', models.CharField(blank=True, max_length=64, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_location_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='stock.stocklocation')),
                ('stock_location_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='stock.stocklocation')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.ubs')),
            ],
            options={
                'db_table': 'stock_movements',
                'permissions': [('transfer_stock', 'Can transfer stock between locations'), ('adjust_stock_request', 'Can request stock adjustment'), ('adjust_stock_approve', 'Can approve stock adjustment'), ('reverse_stock_movement', 'Can reverse/undo a stock movement')],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='stock.stocklocation')),
            ],
            options={
                'db_table': 'stock_balances',
                'permissions': [('view_stock_statement', 'Can view stock statement (movements/extract)')],
            },
        ),
        migrations.CreateModel(
            name='MovementReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reversals', to=settings.AUTH_USER_MODEL)),
                ('original_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='stock.stockmovement')),
                ('reversal_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal_of', to='stock.stockmovement')),
            ],
            options={
                'db_table': 'movement_reversals',
            },
        ),
        migrations.CreateModel(
            name='StockMovementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.stockmovement')),
            ],
            options={
                'db_table': 'stock_movement_items',
                'indexes': [models.Index(fields=['movement'], name='stock_movem_movemen_90cdc0_idx'), models.Index(fields=['item_code'], name='stock_movem_item_co_0136da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['ubs', 'created_at'], name='stock_movem_ubs_id_e2a031_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['ubs', 'movement_type'], name='stock_movem_ubs_id_19f23c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['ubs', 'status'], name='stock_movem_ubs_id_d08ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['ubs', 'active'], name='stock_locat_ubs_id_46a717_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['ubs', 'name'], name='stock_locat_ubs_id_232c95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklocation',
            unique_together={('ubs', 'name')},
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['stock_location'], name='stock_balan_stock_l_cd9294_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['item_code'], name='stock_balan_item_co_cbf8cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockbalance',
            unique_together={('stock_location', 'item_code')},
        ),
        migrations.AddIndex(
            model_name='movementreversal',
            index=models.Index(fields=['created_at'], name='movement_re_created_c478e9_idx'),
        ),
    ]
