# Generated by Django 4.2.27 on 2026-01-29 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatchBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='catalog.batch')),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_balances', to='stock.stocklocation')),
            ],
            options={
                'db_table': 'stock_batch_balances',
                'indexes': [models.Index(fields=['stock_location'], name='stock_batch_stock_l_2b99f4_idx'), models.Index(fields=['batch'], name='stock_batch_batch_i_9cfdb1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockbatchbalance',
            constraint=models.UniqueConstraint(fields=('stock_location', 'batch'), name='ux_balance_location_batch'),
        ),
    ]
