# Generated by Django 4.2.27 on 2026-01-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('stock', '0002_stockbatchbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_items', to='catalog.batch'),
        ),
    ]
