# Generated by Django 4.2.27 on 2026-01-26 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UBS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cnes', models.CharField(blank=True, max_length=32, null=True)),
                ('active', models.BooleanField(default=True)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('address_state', models.CharField(blank=True, max_length=2, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('address_complement', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ubs',
                'indexes': [models.Index(fields=['active'], name='ubs_active_5203d5_idx'), models.Index(fields=['name'], name='ubs_name_31c022_idx')],
            },
        ),
    ]
