# Generated by Django 4.2.27 on 2026-01-26 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cns', models.CharField(max_length=32)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('address_state', models.CharField(blank=True, max_length=2, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('address_complement', models.CharField(blank=True, max_length=255, null=True)),
                ('is_quick_registration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='core.ubs')),
            ],
            options={
                'db_table': 'patients',
                'permissions': [('view_patient_basic', 'Can view patient (basic)'), ('view_patient_full', 'Can view patient (full)')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescriber_name', models.CharField(max_length=255)),
                ('prescriber_registry_type', models.CharField(blank=True, max_length=32, null=True)),
                ('prescriber_registry_number', models.CharField(blank=True, max_length=64, null=True)),
                ('origin_unit', models.CharField(max_length=255)),
                ('prescription_type', models.CharField(max_length=64)),
                ('prescription_date', models.DateField()),
                ('attachment_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='operations.patient')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='core.ubs')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=64)),
                ('series', models.CharField(blank=True, max_length=32, null=True)),
                ('access_key', models.CharField(blank=True, max_length=64, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.ubs')),
            ],
            options={
                'db_table': 'invoices',
                'permissions': [('finalize_invoice', 'Can finalize invoice (generate stock entry)'), ('cancel_invoice', 'Can cancel invoice')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=32)),
                ('approval_reason', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_inventories', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventories', to=settings.AUTH_USER_MODEL)),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='core.ubs')),
            ],
            options={
                'db_table': 'inventories',
                'permissions': [('approve_inventory', 'Can approve inventory'), ('reject_inventory', 'Can reject inventory')],
            },
        ),
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dispensations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='operations.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='operations.prescription')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='core.ubs')),
            ],
            options={
                'db_table': 'dispensations',
                'permissions': [('confirm_dispensation', 'Can confirm dispensation (generate stock out)'), ('cancel_dispensation', 'Can cancel dispensation')],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['ubs', 'prescription_date'], name='prescriptio_ubs_id_a024ff_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'prescription_date'], name='prescriptio_patient_a978e2_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['ubs', 'full_name'], name='patients_ubs_id_f78af5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['ubs', 'cns'], name='patients_ubs_id_44a8cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('ubs', 'cns'), name='ux_patients_ubs_cns'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf__isnull', False)), fields=('ubs', 'cpf'), name='ux_patients_ubs_cpf'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['ubs', 'receipt_date'], name='invoices_ubs_id_a2f4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['ubs', 'status'], name='invoices_ubs_id_d1013a_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('ubs', 'supplier_name', 'invoice_number', 'series'), name='ux_invoice_unique'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['ubs', 'started_at'], name='inventories_ubs_id_0e0c10_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['ubs', 'status'], name='inventories_ubs_id_7ef2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensation',
            index=models.Index(fields=['ubs', 'created_at'], name='dispensatio_ubs_id_88c4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensation',
            index=models.Index(fields=['patient', 'created_at'], name='dispensatio_patient_688c55_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensation',
            index=models.Index(fields=['ubs', 'status'], name='dispensatio_ubs_id_bc4c6b_idx'),
        ),
    ]
