# Generated by Django 4.2.27 on 2026-01-27 01:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_invoice_stock_location_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispensation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='operations.dispensation')),
            ],
            options={
                'db_table': 'dispensation_items',
                'indexes': [models.Index(fields=['dispensation'], name='dispensatio_dispens_45dc02_idx'), models.Index(fields=['item_code'], name='dispensatio_item_co_0ec1e7_idx')],
            },
        ),
    ]
