# Generated by Django 4.2.27 on 2026-01-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('operations', '0003_dispensationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensation',
            name='stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='stock.stocklocation'),
        ),
    ]
