# Generated by Django 4.2.27 on 2026-01-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_dispensation_stock_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('view_patient_basic', 'Can view patient (basic)'), ('view_patient_full', 'Can view full patient sensitive data')]},
        ),
    ]
