# Generated by Django 4.2.27 on 2026-01-29 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('operations', '0005_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensationitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensation_items', to='catalog.batch'),
        ),
        migrations.AddField(
            model_name='dispensationitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensation_items', to='catalog.medicine'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='lot_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='catalog.medicine'),
        ),
    ]
