# Generated by Django 4.2.27 on 2026-01-30 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('stock', '0003_stockmovementitem_batch'),
        ('operations', '0006_dispensationitem_batch_dispensationitem_medicine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='catalog.batch')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_items', to='operations.inventory')),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='stock.stocklocation')),
            ],
            options={
                'db_table': 'inventory_count_items',
                'indexes': [models.Index(fields=['inventory'], name='inventory_c_invento_bd6bd4_idx'), models.Index(fields=['stock_location'], name='inventory_c_stock_l_14f987_idx'), models.Index(fields=['batch'], name='inventory_c_batch_i_063b6a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorycountitem',
            constraint=models.UniqueConstraint(fields=('inventory', 'stock_location', 'batch'), name='ux_inventory_location_batch'),
        ),
    ]
