# Generated by Django 4.2.27 on 2026-03-31 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0007_inventorycountitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('PARTIALLY_RECEIVED', 'PARTIALLY_RECEIVED'), ('RECEIVED', 'RECEIVED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ubs')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dispensation',
            options={'permissions': [('confirm_dispensation', 'Can confirm dispensation (generate stock out)'), ('cancel_dispensation', 'Can cancel dispensation')], 'verbose_name': 'Dispensação', 'verbose_name_plural': 'Dispensações'},
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='operations.patient', verbose_name='Paciente'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=18)),
                ('quantity_received', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='operations.order')),
            ],
        ),
    ]
