# Generated by Django 4.2.11 on 2026-04-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockmovementitem_batch'),
        ('operations', '0009_orderreceiveitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stock.stocklocation'),
        ),
    ]
