# Generated by Django 4.2.11 on 2026-04-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_order_stock_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity_received',
        ),
    ]
