# Generated by Django 4.2.27 on 2026-01-29 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=128)),
                ('object_type', models.CharField(blank=True, max_length=128, null=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='core.ubs')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['ubs', 'created_at'], name='audit_logs_ubs_id_53aa99_idx'), models.Index(fields=['event', 'created_at'], name='audit_logs_event_cbf554_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_logs_object__457405_idx'), models.Index(fields=['correlation_id'], name='audit_logs_correla_953e51_idx')],
            },
        ),
    ]
