# Generated by Django 4.2.27 on 2026-01-29 23:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suppliers',
                'indexes': [models.Index(fields=['name'], name='suppliers_name_ed482a_idx'), models.Index(fields=['cnpj'], name='suppliers_cnpj_f8c836_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('presentation', models.CharField(blank=True, max_length=255, null=True)),
                ('anvisa_code', models.CharField(blank=True, max_length=64, null=True)),
                ('ean', models.CharField(blank=True, max_length=32, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medicines',
                'indexes': [models.Index(fields=['name'], name='medicines_name_017048_idx'), models.Index(fields=['anvisa_code'], name='medicines_anvisa__e5bbfd_idx'), models.Index(fields=['ean'], name='medicines_ean_282baa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=64)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.medicine')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.supplier')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.ubs')),
            ],
            options={
                'db_table': 'batches',
                'permissions': [('manage_catalog', 'Can manage catalog (medicine/supplier/batch)')],
                'indexes': [models.Index(fields=['ubs', 'medicine'], name='batches_ubs_id_a09037_idx'), models.Index(fields=['ubs', 'expiry_date'], name='batches_ubs_id_b6dbe7_idx'), models.Index(fields=['lot_number'], name='batches_lot_num_91814a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('ubs', 'medicine', 'lot_number', 'expiry_date'), name='ux_batch_ubs_medicine_lot_expiry'),
        ),
    ]
