@startuml
left to right direction
skinparam packageStyle rectangle

actor "Administrador Municipal" as Admin
actor "Responsável Técnico (RT)" as RT

rectangle "Sistema de Medicamentos UBS" {
  usecase "Cadastrar Medicamento" as UC_CreateMed
  usecase "Editar Medicamento" as UC_EditMed
  usecase "Inativar Medicamento" as UC_InactivateMed
}

Admin --> UC_CreateMed
Admin --> UC_EditMed
Admin --> UC_InactivateMed

RT --> UC_CreateMed
RT --> UC_EditMed
RT --> UC_InactivateMed
@enduml
